name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        otp:
          - '25.1.2'
          - '24.3.4.7'
          - '23.3.4.9'
        elixir:
          - '1.14.2'
          - '1.13.2'
          - '1.12.3'
          - '1.11.4'
        exclude:
          - otp: '25.1.2'
            elixir: '1.12.3'
          - otp: '25.1.2'
            elixir: '1.11.4'
            # breaks with test/poison/encoder_test.exs:70
            # Clause:    value <- json_string()
            # Generated: "\uFEFF"
            # Assertion with == failed
            # code:  assert to_json(value) == inspect(value)
            # left:  "\"\uFEFF\""
            # right: "\"\\uFEFF\""
          - otp: '23.3.4.9'
            elixir: '1.12.3'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            _build
            deps
            vendor
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
