name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - windows-2022
          - macos-14
        otp:
          - "26.2"
          - "26.1"
          - "26.0"
          - "25.3"
          - "25.2"
          - "25.1"
          - "25.0"
          - "24.3"
          - "24.2"
          - "24.1"
          - "24.0"
          - "23.3"
          - "23.2"
          - "23.1"
          - "23.0"
        elixir:
          - "1.16.1"
          - "1.16.0"
          - "1.15.7"
          - "1.15.6"
          - "1.15.5"
          - "1.15.4"
          - "1.15.3"
          - "1.15.2"
          - "1.15.1"
          - "1.15.0"
          - "1.14.5"
          - "1.14.4"
          - "1.14.3"
          - "1.14.2"
          - "1.14.1"
          - "1.14.0"
          - "1.13.4"
          - "1.13.3"
          - "1.13.2"
          - "1.13.1"
          - "1.13.0"
          - "1.12.3"
          - "1.12.2"
          - "1.12.1"
          - "1.12.0"
          - "1.11.4"
          - "1.11.3"
          - "1.11.2"
          - "1.11.1"
          - "1.11.0"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - uses: actions/cache@v4
        id: mix-cache
        with:
          path: |
            _build
            deps
            vendor
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
